//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.0
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyProduct("Maybe")]
[assembly: AssemblyCopyright("Copyright © Alexander Zaytsev 2011 - 2015")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.2.0")]


